### ISSUE TITLE
The lockfile module dependency doesn't seem to be registered

### ISSUE THREAD

**Issue by HubTou** [pypa/pip-audit#529]
## Bug description

Runtime error when the lockfile module is not present.

Note: I removed this module because no package was claiming it as a requirement (pip list --not-required).

## Reproduction steps

Running pip-audit

## Expected behavior

pip-audit running without ImportError exception

## Screenshots and logs

```
$ pip-audit --progress-spinner off --desc
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cachecontrol/caches/file_cache.py", line 77, in __init__
    from lockfile import LockFile
ImportError: cannot import name 'LockFile' from 'lockfile' (unknown location)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pip-audit", line 8, in <module>
    sys.exit(audit())
  File "/usr/local/lib/python3.9/site-packages/pip_audit/_cli.py", line 370, in audit
    service = args.vulnerability_service.to_service(args.timeout, args.cache_dir)
  File "/usr/local/lib/python3.9/site-packages/pip_audit/_cli.py", line 107, in to_service
    return PyPIService(cache_dir, timeout)
  File "/usr/local/lib/python3.9/site-packages/pip_audit/_service/pypi.py", line 45, in __init__
    self.session = caching_session(cache_dir)
  File "/usr/local/lib/python3.9/site-packages/pip_audit/_cache.py", line 165, in caching_session
    cache=_SafeFileCache(_get_cache_dir(cache_dir, use_pip=use_pip)),
  File "/usr/local/lib/python3.9/site-packages/pip_audit/_cache.py", line 87, in __init__
    super().__init__(directory)
  File "/usr/local/lib/python3.9/site-packages/cachecontrol/caches/file_cache.py", line 87, in __init__
    raise ImportError(notice)
ImportError:
NOTE: In order to use the FileCache you must have
lockfile installed. You can install it via pip:
  pip install lockfile

$ pip install lockfile
Collecting lockfile
  Using cached lockfile-0.12.2-py2.py3-none-any.whl (13 kB)
Installing collected packages: lockfile
Successfully installed lockfile-0.12.2

$ pip-audit --progress-spinner off --desc
No known vulnerabilities found
```

## Platform information

* OS name and version:
FreeBSD MyServer 13.1-RELEASE FreeBSD 13.1-RELEASE releng/13.1-n250148-fc952ac2212 GENERIC amd64

* `pip-audit` version (`pip-audit -V`):
pip-audit 2.4.14

* Python version (`python -V` or `python3 -V`):
Python 3.9.16

* `pip` version (`pip -V` or `pip3 -V`):
pip 23.0.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)

## Additional context

https://github.com/pypa/pip-audit/blob/main/pyproject.toml only has no lockfile dependency:
```
dependencies = [
    "CacheControl[filecache]>=0.12.10",
    # NOTE(ww): Release 2.5.0 is broken, subsequent 2.5.x releases fix it.
    # See: https://github.com/CycloneDX/cyclonedx-python-lib/issues/245
    "cyclonedx-python-lib>=2.0.0,!=2.5.0",
    "html5lib>=1.1",
    "packaging>=23.0.0",  # https://github.com/pypa/pip-audit/issues/464
    "pip-api>=0.0.28",
    "pip-requirements-parser>=32.0.0",
    "resolvelib>=0.8.0",
    "rich>=12.4",
    "toml>=0.10",
]
```

**Comment by woodruffw** [comment]
Thanks for the report!

This error is strange: we require `CacheControl[filecache]`, which depends on either `lockfile` or `filelock` depending on the version being resolved:

https://github.com/ionrock/cachecontrol/commit/f0cd6b49e5c4215137e5c24ac0b46752f0c61e69

As such, `pip-audit` itself should never have a direct dependency on either `lockfile` or `filelock` -- we never use it in first-party code.

How are you installing `pip-audit`? Is it coming from `pip`, or from FreeBSD's ports?

**Comment by HubTou** [comment]
Hello, it was installed from pip.

**Comment by woodruffw** [comment]
Gotcha. In that case, I don't think there's anything we can do here: this is a subdependency, and (as far as I can tell) `CacheControl` does register it correctly via the `filecache` extra. 

It's possible that `pip list --not-required` doesn't catch dependencies from extras, but that would be surprising to me.

**Comment by woodruffw** [comment]
I'm probably going to close this out as not our bug, but one last debugging step: could you run `pip list` and see what version of `CacheControl` you have?

**Comment by HubTou** [comment]
Hello,

I have version 0.12.11

Best regards,

Hubert

**Comment by woodruffw** [comment]
> I have version 0.12.11

Thanks! Yeah, I can see that `CacheControl==0.12.11` does indeed list `lockfile` in its extras:

https://github.com/ionrock/cachecontrol/blob/2e0fbc251d619d8aa843e59aa81dca7d7b007f3c/setup.py#L25

This makes me think that this is maybe a bug in `pip list --not-required`, or maybe that something weird happened during installation (maybe `CacheControl` was already installed but without the appropriate extra, and so re-installing with that extra didn't result in its inclusion in the required set?)

Either way, I think this indicates that the bug is outside of `pip-audit`, since `lockfile` is a subdependency that we don't directly use. Thanks again for reporting.

**Comment by HubTou** [comment]
Hello,
Indeed I filed this as a [pip bug](https://github.com/pypa/pip/issues/11828).
Thanks a lot for your time and thoroughness!
